Reorder code

diff --git a/rpifbss b/rpifbss
--- a/rpifbss
+++ b/rpifbss
@@ -2,6 +2,15 @@
 #
 # rpifbss - Raspberry Pi Framebuffer Slideshow    by rpi-simonz Nov. 2024
 
+# >>>> Configuration section
+
+SECONDS_PER_IMAGE=3
+BLEND_MILLISECONDS=800
+
+MAINTENANCE_MSG_DEFAULT="*** Maintenance running. Please be patient. ***"
+
+# <<<< End
+
 
 function print_info() {
     cat <<EOF
@@ -25,32 +34,6 @@ Ctrl-C ends this program.
 ===============================================================================
 EOF
 }
-
-IMAGE_DIR=${1:-$PWD}
-if [ ! -d "$IMAGE_DIR" ] ; then
-    echo "Error: Provided directory '$IMAGE_DIR' not existing!?"
-    exit 1
-fi
-
-cd $IMAGE_DIR || exit 1
-IMAGE_DIR=${PWD}
-
-
-# >>>> Configuration section
-
-SECONDS_PER_IMAGE=3
-BLEND_MILLISECONDS=800
-
-MAINTENANCE_DIR=${IMAGE_DIR}/maintenance
-MAINTENANCE_MSG_FILE=${MAINTENANCE_DIR}/maintenance.txt
-MAINTENANCE_MSG_DEFAULT="*** Maintenance running. Please be patient. ***"
-
-# <<<< End
-
-
-trap exit INT
-
-MYNAME=$(basename $0)
 
 
 function txtfiles2jpg() {
@@ -102,13 +85,27 @@ function maintenance() {
 
 #=============================================================================
 
-print_info
+IMAGE_DIR=${1:-$PWD}
+if [ ! -d "$IMAGE_DIR" ] ; then
+    echo "Error: Provided directory '$IMAGE_DIR' not existing!?"
+    exit 1
+fi
 
+cd $IMAGE_DIR || exit 1
+IMAGE_DIR=${PWD}
+
+MAINTENANCE_DIR=${IMAGE_DIR}/maintenance
+MAINTENANCE_MSG_FILE=${MAINTENANCE_DIR}/maintenance.txt
+
+MYNAME=$(basename $0)
+
+print_info
 prepare_maintenance_dir
+trap exit INT
 
 while true ; do
     maintenance
     IMAGES=$(find . -maxdepth 1 -type f ! \( -name "*.txt" -o -name "$MYNAME" \) -print | sort)
-    fbi -d /dev/fb0 --noverbose -a --blend $BLEND_MILLISECONDS -t $SECONDS_PER_IMAGE  $IMAGES 
+    fbi -d /dev/fb0 --noverbose -a --blend $BLEND_MILLISECONDS -t $SECONDS_PER_IMAGE  $IMAGES
 done
 
