More flexible IMAGE_DIR: Current working dir or given by first parameter.

diff --git a/rpifbss b/rpifbss
--- a/rpifbss
+++ b/rpifbss
@@ -5,11 +5,11 @@
 
 function print_info() {
     cat <<EOF
-==============================================================================
+===============================================================================
 
 rpifbss - Raspberry Pi Framebuffer Slideshow
 
-This program provides a simple slideshow from a directory of files.
+This program provides a simple framebuffer slideshow from a directory of files.
 It uses the software 'fbi' for that.
 So only still images are possible, no videos.
 
@@ -22,23 +22,32 @@ The slideshow can be manipulated interactively with fbi's key shortcuts.
 
 Ctrl-C ends this program.
 
-==============================================================================
+===============================================================================
 EOF
 }
+
+IMAGE_DIR=${1:-$PWD}
+if [ ! -d "$IMAGE_DIR" ] ; then
+    echo "Error: Provided directory '$IMAGE_DIR' not existing!?"
+    exit 1
+fi
+
+
+# >>>> Configuration section
+
+SECONDS_PER_IMAGE=3
+BLEND_MILLISECONDS=800
+
+MAINTENANCE_DIR=${IMAGE_DIR}/maintenance
+MAINTENANCE_MSG_FILE=${MAINTENANCE_DIR}/maintenance.txt
+MAINTENANCE_MSG_DEFAULT="*** Maintenance running. Please be patient. ***"
+
+# <<<< End
 
 
 trap exit INT
 
 MYNAME=$(basename $0)
-
-SECONDS_PER_IMAGE=3
-BLEND_MILLISECONDS=800
-
-IMAGE_DIR=~/dia
-MAINTENANCE_DIR=${IMAGE_DIR}/maintenance
-
-MAINTENANCE_MSG_FILE=${MAINTENANCE_DIR}/maintenance.txt
-MAINTENANCE_MSG_DEFAULT="*** Maintenance running. Please be patient. ***"
 
 
 function txtfiles2jpg() {
